# How to run: gcloud builds submit --config cloudbuild.yaml .
steps:
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kuasar-frontend', '.']
  - id: push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kuasar-frontend']
  - id: deploy
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kuasar-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kuasar-frontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast1'
      - '--allow-unauthenticated'
      - '--project'
      - '$PROJECT_ID'
      - '--vpc-connector=connector-kuasar'
      - '--vpc-egress=all-traffic'
images:
  - 'gcr.io/$PROJECT_ID/kuasar-frontend'
